version: "3.3"

services:
  game-server:
    build:
      context: .
      dockerfile: GameServer.Dockerfile
    ports:
      - 8080:80
    networks:
      edupra-network:
        ipv4_address: 172.20.0.2
    environment:
      - MODEL_ENDPOINT=http://172.20.0.3:7314

  model-server:
    build:
      context: .
      dockerfile: ModelServer.Dockerfile
    ports:
      - :7314
    volumes:
      - ./models:/models
    networks:
      edupra-network:
        ipv4_address: 172.20.0.3
    environment:
      # Set MODEL_PATH here for example:
      # - MODEL_PATH=/models/1/1_20240512_1416_52_764016_1.tar
      - REDIS_URL=redis://172.20.0.4:6379/0

  redis:
    image: redis:latest
    restart: on-failure
    ports:
      - :6379
    networks:
      edupra-network:
        ipv4_address: 172.20.0.4

networks:
  edupra-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1
